<a href="https://colab.research.google.com/github/deepnov/dnutties/blob/main/LearnML2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_list={1,2,3}
my_list
np.array(my_list)


array({1, 2, 3}, dtype=object)

In [ ]:
import numpy as np
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [ ]:
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
import numpy as np
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
np.random.rand(2,3)

array([[0.65834984, 0.59599523, 0.11493263],
       [0.53388745, 0.61910341, 0.08962908]])

In [ ]:
import numpy as np
np.random.randn(7)
#std normal distribution

array([ 1.6250729 ,  0.03580549, -2.1751783 , -0.9606873 , -0.06448493,
        0.29406606, -0.04294395])

In [ ]:
import numpy as np
np.random.randint(1,99,9)
#3rd argument for number of random numbers needed

array([ 7, 79, 59,  4, 38, 13, 62, 59,  7])

July 24th 2023 session starts below:

In [ ]:
import numpy as np
array=np.arange(15)
array
array.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
import numpy as np
array=np.random.randint(0,50,10)
print(array)
print(array.max())
array.min()

[25 17 43 39 44 30 40  8  2  5]
44


2

In [ ]:
import numpy as np
array=np.random.randint(0,50,10)
print(array)
array[3:7]=999 #replace particular values in array
print(array)

[19 41 24 33 34 37  5 23 49 36]
[ 19  41  24 999 999 999 999  23  49  36]


In [ ]:
import numpy as np
array=np.random.randint(0,50,25).reshape(5,5)
print(array)
array > 21

[[49 36 26  9  0]
 [38 44 46 23 30]
 [26 10 49 33 19]
 [44 36  5 44 23]
 [11 44 42 32  8]]


array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True, False]])

In [ ]:
import numpy as np
array=np.arange(10)
print(array)
print(array+array)
print(array*2)
np.sin(array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

Pandas - data analysis and data preparation

In [ ]:
import numpy as np
import pandas as pd
labels =['A','B','C']
my_data=[100,200,300]
array=np.array(my_data)
d={'A':100,'B':200,'C':300}
pd.Series(d)

A    100
B    200
C    300
dtype: int64

DataFrames is a 2D labeled data structure with columns of different types.

In [9]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df = pd.DataFrame(randn(5,4),['a','b','c','d','e'],['x','y','z','t'])
print(df)
print(df['t']) #series in 2D is dataframe
print(df.loc['a'])
df['TEST']=df['x']+df['z']
print(df)
df[df > 0].dropna()

          x         y         z         t
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509
a    0.503826
b    0.605965
c   -0.589001
d    0.955057
e    0.683509
Name: t, dtype: float64
x    2.706850
y    0.628133
z    0.907969
t    0.503826
Name: a, dtype: float64
          x         y         z         t      TEST
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762


x         y         z         t      TEST
a  2.706850  0.628133  0.907969  0.503826  3.614819
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [15]:
import numpy as np
import pandas as pd
data = {'Country': ['USA', 'USA', 'France','France','Germany','Germany'],'Person':['Sam','Amy','Carhile','Richard','John','Frank'],'Sales': [250, 300, 125, 500, 350, 200]}
df = pd.DataFrame(data)
print(df)
df.groupby('Country').sum(numeric_only=False)

   Country   Person  Sales
0      USA      Sam    250
1      USA      Amy    300
2   France  Carhile    125
3   France  Richard    500
4  Germany     John    350
5  Germany    Frank    200


Person  Sales
Country                       
France   CarhileRichard    625
Germany       JohnFrank    550
USA              SamAmy    550

In [23]:
import pandas as pd
df = pd.read_csv('Salaries.csv',low_memory=False)
print(df.TotalPayBenefits.mean())
df

93692.55481056681


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]