<a href="https://colab.research.google.com/github/deepnov/dnutties/blob/main/LearnML2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_list={1,2,3}
my_list
np.array(my_list)


array({1, 2, 3}, dtype=object)

In [ ]:
import numpy as np
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [ ]:
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
import numpy as np
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
np.random.rand(2,3)

array([[0.65834984, 0.59599523, 0.11493263],
       [0.53388745, 0.61910341, 0.08962908]])

In [ ]:
import numpy as np
np.random.randn(7)
#std normal distribution

array([ 1.6250729 ,  0.03580549, -2.1751783 , -0.9606873 , -0.06448493,
        0.29406606, -0.04294395])

In [ ]:
import numpy as np
np.random.randint(1,99,9)
#3rd argument for number of random numbers needed

array([ 7, 79, 59,  4, 38, 13, 62, 59,  7])

July 24th 2023 session starts below:

In [2]:
import numpy as np
array=np.arange(15)
array
array.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
import numpy as np
array=np.random.randint(0,50,10)
print(array)
print(array.max())
array.min()

[25 17 43 39 44 30 40  8  2  5]
44


2

In [11]:
import numpy as np
array=np.random.randint(0,50,10)
print(array)
array[3:7]=999 #replace particular values in array
print(array)

[19 41 24 33 34 37  5 23 49 36]
[ 19  41  24 999 999 999 999  23  49  36]


In [12]:
import numpy as np
array=np.random.randint(0,50,25).reshape(5,5)
print(array)
array > 21

[[49 36 26  9  0]
 [38 44 46 23 30]
 [26 10 49 33 19]
 [44 36  5 44 23]
 [11 44 42 32  8]]


array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True, False]])

In [13]:
import numpy as np
array=np.arange(10)
print(array)
print(array+array)
print(array*2)
np.sin(array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])