<a href="https://colab.research.google.com/github/deepnov/dnutties/blob/main/LearnML2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
my_list={1,2,3}
my_list
np.array(my_list)


array({1, 2, 3}, dtype=object)

In [9]:
import numpy as np
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [12]:
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
import numpy as np
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
import numpy as np
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
import numpy as np
np.random.rand(2,3)

array([[0.65834984, 0.59599523, 0.11493263],
       [0.53388745, 0.61910341, 0.08962908]])

In [22]:
import numpy as np
np.random.randn(7)
#std normal distribution

array([ 1.6250729 ,  0.03580549, -2.1751783 , -0.9606873 , -0.06448493,
        0.29406606, -0.04294395])

In [25]:
import numpy as np
np.random.randint(1,99,9)
#3rd argument for number of random numbers needed

array([ 7, 79, 59,  4, 38, 13, 62, 59,  7])